id: P001705
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD159445
  title: ཀུན་གཟིགས་མ་ཧཱ་པཎྚི་ཏ་པདྨ་ཚེ་དབང་མཆོག་གི་རྗེས་དྲན་སྐྱོ་གདུང་གི་མིག་ཆུ་དྲོན་མོ།
  author: ''
  volumes:
    deeab38305ce45b0abbce47574ce0a73:
      image_group_id: I2PD19680
      title: ''
      volume_number: 1
      total_pages: 182
